name: 测试

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 下载 CloudFlare IP 列表
        run: |
          wget -qO- https://www.cloudflare-cn.com/ips-v4/ | tee ip.txt

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install aiohttp ewma async-timeout

      - name: 测速
        run: |
          set -e
          python your_script_name.py -cfcolo HKG -sl 5 -n 800 -dn 5 -o HKG.csv -f ip.txt
          rm -f ip.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add HKG.csv
          git commit -m "测试"
          git push