name: CFST

on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 16:00 UTC daily (midnight Beijing time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 下载 CloudFlare IP 列表
        run: |
          wget -qO- https://www.cloudflare-cn.com/ips-v4/ | tee ip.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install aiohttp tqdm ipaddress

      - name: 测速
        run: |
          set -e
          python CFST.py -cfcolo HKG -sl 5 -n 800 -dn 5 -o HKG.csv

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add files for commit, including ip.txt and any generated .txt files
          git add ip.txt *.csv *.txt

          # Commit if there are any changes
          if ! git diff --cached --quiet; then
            git commit -m "test"
            git push
          else
            echo "No changes to commit."
          fi