name: Sync-repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          path: target

      - name: Checkout sync repository
        uses: actions/checkout@v3
        with:
          repository: ImLTHQ/edge-tunnel
          path: source

      - name: Sync files
        run: |
          rsync -av --delete source/ target/

      - name: Configure Git
        working-directory: target
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote set-url origin git@github.com:${{ github.repository }}

      - name: Commit and push changes
        working-directory: target
        run: |
          git add .
          git commit -m "从上游同步" || echo "没有更改"
          git push origin main